### ISSUE TITLE
Url Bar width and box-shadow have problem?

### ISSUE THREAD

**Issue by vuvansang07** [muckSponge/MaterialFox#153]
1. How to make #urlbar width = #urlbar-results width
I don't know how to do it. I using MaterialFox but when I customize add Search Box or Flexible Space Box, #urlbar width is narrowed, but #urlbar-results width is not changing?
Have any way to make it is the same or using via useChrome.js (i don't know more and how to make it is working). 
I don't think --item-padding-start and --item-padding-end can fix it.
![image](https://user-images.githubusercontent.com/49393076/64979657-56ae9000-d8e2-11e9-99ca-f2bce1c225a4.png)

2. How to remove box-shadow from #urlbar-results
I know you using a trick to remove box-shadow
#urlbar-results {
  background: 0 !important;
}

.urlbarView-body-inner,
.search-panel-one-offs-header,
.search-panel-one-offs {
  background: var(--arrowpanel-background) !important;
}

But box-shadow is effected by #urlbar-results, i just try this but it is not working. I don't want using a trick because i want keep background color
#urlbar-results {
  box-shadow: none !important;
}

3. How to make #urlbar-results like Edge in Windows 10
I like this because it is simple, friendly. But i don't like tabbar and bookmarks of Edge
![image](https://user-images.githubusercontent.com/49393076/64979034-08e55800-d8e1-11e9-910a-7f8a6e60fc59.png)

**Comment by muckSponge** [comment]
1. Should be resolved in latest commit on master (you'll need to be using FF70+).
2. `#urlbar { box-shadow: none !important; }`
3. This is outside of scope of the issue. For more help regarding this, I'd suggest posting in the [Firefox CSS subreddit](https://www.reddit.com/r/FirefoxCSS/) and/or learning how to do it yourself (some useful links in that sub).

**Comment by vuvansang07** [comment]
Hi tks, i just fix it by userChrome.js.
But when update FF ver 70, i need fix again, hic
Do you know how to disable Popup Require Master Password in a first open Firefox?
I not request any site login, but popup still show in a little time

________________________________

**Comment by vuvansang07** [comment]
MaterialFox FF70 very nice, tks for your update 😍
________________________________
