### ISSUE TITLE
HTTP passwords are marked secure

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#26]
When looking at a [normal HTTP site](http://http.badssl.com/), the lock changes to an info icon like Chrome (please recommend users to enable `security.insecure_connection_text.enabled` for the "Not Secure" text - see PR #27).

However, when looking at a [HTTP site with a password field](http://http-password.badssl.com/), the info icon persists but the normal lock icon persists too, which is a huge security issue.

I would recommend swapping the broken lock with the warning icon and when the icon exists, make the whole text red, [like Chrome in October](https://blog.chromium.org/2018/05/evolving-chromes-security-indicators.html) (also [available now on broken HTTPS](https://wrong.host.badssl.com/), FWIW).

Firefox 63.0b6, macOS 10.13.6.

**Comment by muckSponge** [comment]
> When looking at a [normal HTTP site](http://http.badssl.com/), the lock changes to an info icon like Chrome (please recommend users to enable `security.insecure_connection_text.enabled` for the "Not Secure" text - see PR #27).

Merged pull request so this should be working now, though it won't work for the wrong host case.

> However, when looking at a [HTTP site with a password field](http://http-password.badssl.com/), the info icon persists but the normal lock icon persists too, which is a huge security issue.

Fixed in d763d69ef6ab0b67c0e5a86be20303fdebd79229.

> I would recommend swapping the broken lock with the warning icon and when the icon exists, make the whole text red, [like Chrome in October](https://blog.chromium.org/2018/05/evolving-chromes-security-indicators.html) (also [available now on broken HTTPS](https://wrong.host.badssl.com/), FWIW).

Not sure this is possible in Firefox for the broken HTTPS case because it doesn't provide selectors for it. The only selector for it is ```.unknownIdentity``` but this is also added for virtually every "insecure" case, including the plain old HTTP case, so I have no way to distinguish it. I should be able to do something about the HTTP password case though. Will tackle that a bit later.

**Comment by Madis0** [comment]
> Not sure this is possible in Firefox for the broken HTTPS case because it doesn't provide selectors for it.

Oops, I meant the broken HTTPS on Chromium, as in the red indicator can already be viewed.

> The only selector for it is `.unknownIdentity` but this is also added for virtually every "insecure" case, including the plain old HTTP case, so I have no way to distinguish it. 

`.insecureLoginForms`, no?

> I should be able to do something about the HTTP password case though. Will tackle that a bit later.

You could just replace the broken lock with the red triangle for now.

**Comment by muckSponge** [comment]
Just for clarification; I'd like to make text red and provide a warning icon for broken HTTPS like in Chrome, but Firefox does not provide a selector for that specific case.

Insecure forms now make text red and have a warning icon.

Please let me know what you think of these changes :)

**Comment by Madis0** [comment]
I guess Firefox doesn't provide that as they don't want to make the indicator and full-page warning conflict. I recall that the broken lock should still appear when you ignore the full-page warning.

**Comment by muckSponge** [comment]
https://wrong.host.badssl.com/ still won't feature any "Not secure" text purely because Firefox doesn't add it to the DOM but the correct icon and colour should be shown throughout.

**Comment by muckSponge** [comment]
I've tested b33f56f7473753d0f4ed5846d1f85e4fab3305ab under each scenario described here and many more:
```
unknownIdentity
verifiedIdentity
verifiedDomain
mixedActiveBlocked
mixedDisplayContent
mixedDisplayContentLoadedActiveBlocked
certUserOverriden
mixedActiveContent
insecureLoginForms
chromeUI
extensionPage
```
And it behaves as closely as possible to Chrome. I'll close this but feel free to open if there's something I've missed or it requires further discussion.

**Comment by Madis0** [comment]
On 63.0b9 as of 8ca2049, [HTTP passwords](http://http-password.badssl.com/) are displayed the same as [other HTTP sites ](http://http.badssl.com/). When forcing the broken padlock for all HTTP (`security.insecure_connection_icon.enabled`), the info icon resets to the Firefox one.

**Comment by Madis0** [comment]
That commit fixed the Firefox-style info icons with the mentioned flag enabled but not extension pages (e.g. uBlock Origin settings). 

Also there is still no more red triangle on HTTP passwords, is your goal to be consistent with current stable Chromium? (so I'd assume you'll add it when version 70 gets released)

**Comment by muckSponge** [comment]
I'm on 70.0.3538.35 and I don't see a red triangle for HTTP passwords. Is there something I'm missing?

**Comment by muckSponge** [comment]
Oh I see, it's hidden behind ```chrome://flags/#enable-mark-http-as``` ```Enabled (mark as actively dangerous)```. Is this going to become the default at some point? Because currently, the default in 70 is to display the grey "Not secure" text with the info icon, not red warning icon and text.

**Comment by Madis0** [comment]
Not sure how development versions work, but stable will [add a red triangle when writing text to any HTTP input](https://blog.chromium.org/2018/05/evolving-chromes-security-indicators.html). Since Firefox does not currently check for that, the best you can do (without an extension) is make it work the way it already does - marking pages with password fields insecure.

**Comment by muckSponge** [comment]
Warning icon will now appear for HTTP passwords in Firefox.

**Comment by Madis0** [comment]
Can confirm it working now. 

The setting `security.insecure_connection_icon.enabled` doesn't change anything, but it is a hidden, default-disabled setting anyway... You can support it if you prefer, but I believe Chromium will change the "Not Secure" default to red triangle soon anyway (rumored early next year), so it could be the default here too.

**Comment by muckSponge** [comment]
I should probably support that pref but not sure if I can be bothered. I'll have a think about it.

**Comment by muckSponge** [comment]
I'll leave it as is and close this issue.
